WIP: module Dashboard.View
KSF-Media/gitlab-dashboard pull request #6
Opened 2017-10-31 23:37 UTC by zudov

That module contains functions that produce halogen's HTML given
certain parameters. Most of them are ported from corresponding
javascript functions fairly directly.

Ported functionality:

- [X] `wrap_cell` -> `cell :: ∀ p i. HTML p i -> HTML p i` 
- [X] `author_img` -> `authorImage :: ∀ p i. String -> HTML p i`
- [X] `fa_icon` ->`fontAwesome :: ∀ p i. String -> Array ClassName -> HTML p i`
- [ ] `status2icon`
- [ ] `format_status`
- [ ] `format_commit`
- [ ] `format_times`
- [ ] `format_pipeline`

2017-11-05 22:06 UTC, zudov commented
Ready for review, types are quite placeholderish and would require careful replacement when merging with Model branch.

2017-11-06 08:09 UTC, f-f requested changes

2017-11-06 08:09 UTC, f-f commented on src/Dashboard/View.purs
> +import Halogen.HTML
Should this be `import Halogen.HTML (HTML)`?

2017-11-06 08:12 UTC, f-f commented
Looks good. I guess I should now rebase and unify the types.
Did you tested if it visualizes something meaningful?
Also, should we tackle the "refresh the data every 30 secs and pass it to Halogen" in another PR/Issue?

2017-11-07 14:20 UTC, f-f approved these changes

2017-11-07 14:20 UTC, merged